// <auto-generated />
namespace BontoBuyWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedDateType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDateType));
        
        string IMigrationMetadata.Id
        {
            get { return "201510191714298_addedDateType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
